In [1]:
import numpy as np

20 evenly spaced numbers from 0 to 1
The integers 0–19 arranged as 4 rows × 5 columns
A 3×3 array of zeros
A 3×3 identity matrix

In [27]:
a = np.linspace(0,20)
a

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [31]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
x = np.random.randn(100)
x

array([ 0.21254876, -1.98178289,  0.4650662 , -0.28718605, -0.78075987,
       -0.55635689,  1.27822241,  1.64373282,  0.12231203,  0.22439001,
       -0.92248323,  0.13131887,  0.87288466,  0.32085664,  0.20831491,
        0.4253668 , -0.46048338, -2.95432655,  1.03097465, -0.89696341,
       -1.40966363, -0.26579106,  1.01000087,  0.18666354,  0.0989057 ,
        1.88396583, -0.9118919 , -1.54213073, -0.93821789, -0.08015975,
       -1.30004623, -0.13534931, -0.83773963,  0.90468817,  1.56065926,
       -1.41699244,  0.63894841,  1.01750864,  1.08111876, -0.80613759,
        1.32834048, -0.93992057, -1.27230631, -0.52596062, -1.2908835 ,
       -0.98975338, -1.03457368, -0.77139484,  0.74176046, -0.63249767,
        0.07478023,  0.82817919, -0.3612151 , -0.6365774 , -0.68154369,
       -0.67709485,  0.82621471,  0.03799297, -1.83876641,  1.95717642,
       -0.36878274,  0.23383847, -1.04293698,  2.16785009, -0.16401541,
        0.41905507, -0.33363447, -0.00708998,  0.25950612,  0.82939693,
       -0.27420207, -1.01556816,  0.54019528, -0.91408268, -1.02445119,
        1.54645067, -0.73202539,  0.82802198,  0.12461121, -0.22891815,
       -0.360197  , -0.26854708,  1.31743913,  0.1925154 , -1.3087143 ,
       -0.9435029 ,  2.55937773, -0.21814506, -1.83214077, -0.30982609,
       -3.08920848, -0.86598744, -1.33327714,  0.14196978, -0.0306085 ,
        1.60433509, -0.56107834,  1.42617071,  0.64660054,  0.99530448])

In [38]:
x > 1

array([False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False,  True, False, False,  True, False,
       False, False, False, False, False, False, False,  True, False,
       False,  True,  True, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False,  True, False,  True, False,
       False])

In [47]:
x[x > 1]= 0 

(x>1).sum()

np.int64(0)

In [64]:
p = np.array([1, 0, 1, 1, 0, 0, 1, 1])   # model said
y = np.array([1, 0, 0, 1, 1, 0, 1, 0])   # reality

In [65]:
tp = ((p == 1) & (y == 1)).sum()

In [66]:
# fp
fp = ((p == 1) & (y == 0)).sum()

In [67]:
# fn
fn = ((p == 0) & (y == 1)).sum()

In [68]:
# precision = tp / (tp+fp)
pre = tp / (tp+fp)
# recall = tp / (tp+fn)
rec = tp / (tp+fn)

print(p, r)

[1 0 1 1 0 0 1 1] 0.75

In [2]:
import numpy as np

In [6]:
p = np.random.randint(0,2,20)
y = np.random.randint(0,2,20)

In [16]:
tp = ((p==1) &(y==1)).sum()

fp = ((p==1) & (y==0)).sum()

fn = ((p==0) & (y==1)).sum()

precision = tp / (tp+fp)
recall = tp / (tp+fn)
print(
precision, recall)

0.6923076923076923 0.6923076923076923

In [35]:
x = np.arange(20).reshape(5,4)
print(x.mean(axis=1).shape,
x.mean(axis=0))

(5,) [ 8.  9. 10. 11.]

In [47]:
new_y = x - x.mean(axis=0)

new_y_2 = new_y / new_y.std(axis=0)
print(new_y_2, new_y_2.mean(axis = 0), new_y_2.std(axis = 0))

[[-1.41421356 -1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356  1.41421356]] [0. 0. 0. 0.] [1. 1. 1. 1.]

In [60]:
new = np.linspace(0,1,10)
new_lab = np.where(new>0.3, 1, 0)

new_lab.sum()

np.int64(7)

In [76]:
m = x.astype(float)
m[0,1] = np.nan
m[3, 1] = np.nan
m[2, 3] = np.nan
np.isnan(m).sum(axis=0)

array([0, 2, 0, 1])

In [79]:
m.mean(axis=0)
np.nanmean(m, axis = 0)

array([ 8.        , 10.33333333, 10.        , 11.        ])

In [2]:
import numpy as np

In [19]:
a = np.linspace(0,1,20).reshape(5,4)
mean = np.mean(a, axis = 0)
std = np.std(a, axis = 0)
print(mean,std)

z = (a - mean) / std 
print(z)
print(z.mean(axis=0))
print(z.std(axis=0))

[0.42105263 0.47368421 0.52631579 0.57894737] [0.29772917 0.29772917 0.29772917 0.29772917]
[[-1.41421356e+00 -1.41421356e+00 -1.41421356e+00 -1.41421356e+00]
 [-7.07106781e-01 -7.07106781e-01 -7.07106781e-01 -7.07106781e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.72896959e-16]
 [ 7.07106781e-01  7.07106781e-01  7.07106781e-01  7.07106781e-01]
 [ 1.41421356e+00  1.41421356e+00  1.41421356e+00  1.41421356e+00]]
[-4.44089210e-17 -4.44089210e-17 -4.44089210e-17  3.10862447e-16]
[1. 1. 1. 1.]

In [22]:
import pandas as pd

In [95]:
df = pd.DataFrame({
    "col_a": [1,2,3,4,6],
    "col_b": ["a", "b","g", "c", "d"],
    "col_c": [9.9,8.7,7.6,6.3,0.2],
})
print(df)
print(df.dtypes)

   col_a col_b  col_c
0      1     a    9.9
1      2     b    8.7
2      3     g    7.6
3      4     c    6.3
4      6     d    0.2
col_a      int64
col_b        str
col_c    float64
dtype: object

In [96]:
df.col_a

0    1
1    2
2    3
3    4
4    6
Name: col_a, dtype: int64

In [97]:
df["col_a"]

0    1
1    2
2    3
3    4
4    6
Name: col_a, dtype: int64

In [98]:
sub = df[df["col_a"]>3]

sub
sub.loc[3]

col_a      4
col_b      c
col_c    6.3
Name: 3, dtype: object

In [100]:
sub.iloc[0]

col_a      4
col_b      c
col_c    6.3
Name: 3, dtype: object

In [101]:
df["new_name"] = df["col_a"] * df["col_c"]
df

   col_a col_b  col_c  new_name
0      1     a    9.9       9.9
1      2     b    8.7      17.4
2      3     g    7.6      22.8
3      4     c    6.3      25.2
4      6     d    0.2       1.2

In [102]:
df = df.rename(columns = {"new_name":"col_d"})

In [103]:

df

   col_a col_b  col_c  col_d
0      1     a    9.9    9.9
1      2     b    8.7   17.4
2      3     g    7.6   22.8
3      4     c    6.3   25.2
4      6     d    0.2    1.2

In [104]:
df = df.drop(columns = "col_d")

In [105]:
df

   col_a col_b  col_c
0      1     a    9.9
1      2     b    8.7
2      3     g    7.6
3      4     c    6.3
4      6     d    0.2

In [106]:
df = df.sort_values(by = "col_c", ascending = False)
df

   col_a col_b  col_c
0      1     a    9.9
1      2     b    8.7
2      3     g    7.6
3      4     c    6.3
4      6     d    0.2

In [117]:
df[(df["col_a"]>1) &(df["col_c"]>1)]

   col_a col_b  col_c
1      2     b    8.7
2      3     g    7.6
3      4     c    6.3

In [ ]:
df[[df["col_a">2]&df["col_c">7.6]]]

In [3]:
import pandas as pd 
import numpy as np

In [ ]:
p = np.array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0])
y = np.array([1, 0, 0, 1, 1, 0, 1, 0, 0, 1])

tp = ((y == 1) & (p == 1)).sum()
fp = ((y == 0) & (p == 1)).sum()
fn = ((y == 1) & (p == 0)).sum()

print(tp, fp, fn)

precis = tp / (tp+fp)
// from everything the model predicts true how many are real true
rec = tp / (tp+fn)
// from everything thats true how many did the model predicts as true 
print(precis, rec)

3 2 2
0.6 0.6

In [36]:
import sys
import pandas as pd
from pathlib import Path

ROOT = Path(r"C:\ml_eng_prep_2026\project-1-secom-yield")
INTERIM = ROOT / "data" / "interim"
sys.path.insert(0, str(ROOT))

from src.load import load_secom

In [38]:

X, y, ts = load_secom()

In [39]:
print(X.shape, y.shape, ts.shape)

(1567, 590) (1567,) (1567,)

In [51]:
X.isna().mean().sort_values(ascending = False).head(10)

sensor_292    0.911934
sensor_293    0.911934
sensor_158    0.911934
sensor_157    0.911934
sensor_492    0.855775
sensor_085    0.855775
sensor_358    0.855775
sensor_220    0.855775
sensor_244    0.649649
sensor_517    0.649649
dtype: float64

In [57]:
(X.isna().mean() > 0.45).sum()

np.int64(32)

In [58]:
y.value_counts()

fail
0    1463
1     104
Name: count, dtype: int64

In [59]:
y.value_counts(normalize = True)

fail
0    0.933631
1    0.066369
Name: proportion, dtype: float64

In [69]:
top_share = X.apply(lambda s: s.value_counts(normalize=True).iloc[0])
(top_share > 0.99).sum()

np.int64(122)

In [82]:
miss = X.isna().mean()
top_share = X.apply(lambda s: s.value_counts(normalize=True).iloc[0])

drop = (miss > 0.45) | (top_share > 0.99)
print(drop.sum(),

(~drop).sum())

X.isna().mean().sort_values(ascending=False)

a = X["sensor_292"].isna()
b = X["sensor_293"].isna()
(a == b).value_counts(normalize=True)

154 436

True    1.0
Name: proportion, dtype: float64

In [3]:
import numpy as np 
import pandas as pd

In [4]:
arr = np.random.randn(5,4)

In [ ]:
arr

array([[ 0.66196112, -1.07146521, -0.79766578,  0.65819098],
       [ 0.30409996,  0.39209346, -0.73576167, -0.88953558],
       [ 0.88517722,  0.52209245,  2.54125714,  0.57290497],
       [-0.26556396,  2.94306847, -0.49897937, -0.03761648],
       [ 0.33258333,  1.25092982,  1.03761124, -0.40226713]])

In [7]:
mu = np.mean(arr, axis = 0)
sd = np.std(arr, axis = 0)

In [9]:
new_arr = (arr - mu) / sd

In [14]:
new_arr.mean(axis=0)

array([5.55111512e-17, 1.11022302e-17, 2.22044605e-17, 0.00000000e+00])

In [15]:
new_arr.std(axis=0)

array([1., 1., 1., 1.])

In [20]:
testhash = {
    "category": ['A', 'B', 'C', 'A', 'A', 'B', 'B', 'C'],
    "shift": ['Day', 'Night', 'Day', 'Night', 'Day', 'Night', 'Night', 'Night'],
    "value": [1,2,3,1,2,5,2,5],
    "date": ["2026-09-01", "2026-09-01", "2026-09-02", "2026-09-02", "2026-09-03", "2026-09-03", "2026-09-04", "2026-09-04"]


}

df = pd.DataFrame(testhash)
print(df)

  category  shift  value        date
0        A    Day      1  2026-09-01
1        B  Night      2  2026-09-01
2        C    Day      3  2026-09-02
3        A  Night      1  2026-09-02
4        A    Day      2  2026-09-03
5        B  Night      5  2026-09-03
6        B  Night      2  2026-09-04
7        C  Night      5  2026-09-04

In [23]:
df.groupby("category")["value"].mean()

category
A    1.333333
B    3.000000
C    4.000000
Name: value, dtype: float64

In [26]:
df.groupby("category")["value"].agg(["mean", "std", "count"])

              mean       std  count
category
A         1.333333  0.577350      3
B         3.000000  1.732051      3
C         4.000000  1.414214      2

In [28]:
df.groupby(["category", "shift"])["value"].mean()

category  shift
A         Day      1.5
          Night    1.0
B         Night    3.0
C         Day      3.0
          Night    5.0
Name: value, dtype: float64

In [29]:
df.groupby(["category", "shift"])["value"].mean().reset_index()

  category  shift  value
0        A    Day    1.5
1        A  Night    1.0
2        B  Night    3.0
3        C    Day    3.0
4        C  Night    5.0

In [37]:
df.loc[0, "value"] = np.nan
df
print(df.groupby("category")["value"].count())
print(df.groupby("category")["value"].size())

category
A    2
B    3
C    2
Name: value, dtype: int64
category
A    3
B    3
C    2
Name: value, dtype: int64

In [41]:
df.loc[df.groupby("category")["value"].idxmax()]

  category  shift  value        date
4        A    Day    2.0  2026-09-03
5        B  Night    5.0  2026-09-03
7        C  Night    5.0  2026-09-04

In [44]:
results = pd.DataFrame({
    "model":     ["logreg"] * 3 + ["xgb"] * 3,
    "fold":      [0, 1, 2, 0, 1, 2],
    "precision": [0.18, 0.15, 0.20, 0.25, 0.22, 0.27],
    "recall":    [0.40, 0.35, 0.42, 0.30, 0.33, 0.28],
})

In [45]:
results

    model  fold  precision  recall
0  logreg     0       0.18    0.40
1  logreg     1       0.15    0.35
2  logreg     2       0.20    0.42
3     xgb     0       0.25    0.30
4     xgb     1       0.22    0.33
5     xgb     2       0.27    0.28

In [50]:
results.groupby("model").agg(["mean", "std"]).round(3).T

model           logreg    xgb
fold      mean   1.000  1.000
          std    1.000  1.000
precision mean   0.177  0.247
          std    0.025  0.025
recall    mean   0.390  0.303
          std    0.036  0.025

In [1]:
import pandas as pd 
import numpy as np

In [2]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "name": ["Amy", "Ben", "Cho"],
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 1, 2, 4],
    "amount": [250, 80, 120, 300],
})

In [5]:
pd.merge(customers, orders, how = "inner", on = "customer_id")

   customer_id name  order_id  amount
0            1  Amy       101     250
1            1  Amy       102      80
2            2  Ben       103     120

In [6]:
pd.merge(customers, orders, how = "left", on = "customer_id")

   customer_id name  order_id  amount
0            1  Amy     101.0   250.0
1            1  Amy     102.0    80.0
2            2  Ben     103.0   120.0
3            3  Cho       NaN     NaN

In [8]:
pd.merge(customers, orders, on = "customer_id", how = "outer", indicator = True)

   customer_id name  order_id  amount      _merge
0            1  Amy     101.0   250.0        both
1            1  Amy     102.0    80.0        both
2            2  Ben     103.0   120.0        both
3            3  Cho       NaN     NaN   left_only
4            4  NaN     104.0   300.0  right_only

In [13]:
orders_copy = orders.rename(columns = {"customer_id":"cust_id"})
orders_copy

   order_id  cust_id  amount
0       101        1     250
1       102        1      80
2       103        2     120
3       104        4     300

In [15]:
pd.merge(customers, orders_copy, left_on = "customer_id", right_on = "cust_id", how = "outer")

   customer_id name  order_id  cust_id  amount
0          1.0  Amy     101.0      1.0   250.0
1          1.0  Amy     102.0      1.0    80.0
2          2.0  Ben     103.0      2.0   120.0
3          3.0  Cho       NaN      NaN     NaN
4          NaN  NaN     104.0      4.0   300.0

In [ ]:
pd.concat([customers, orders], axis = 0)

   customer_id name  order_id  amount
0            1  Amy       NaN     NaN
1            2  Ben       NaN     NaN
2            3  Cho       NaN     NaN
0            1  NaN     101.0   250.0
1            1  NaN     102.0    80.0
2            2  NaN     103.0   120.0
3            4  NaN     104.0   300.0

In [18]:
pd.concat([customers, orders], axis = 1)

   customer_id name  order_id  customer_id  amount
0          1.0  Amy       101            1     250
1          2.0  Ben       102            1      80
2          3.0  Cho       103            2     120
3          NaN  NaN       104            4     300

In [21]:
orders_shifted = orders.copy()
orders_shifted.index = [10, 20, 30, 40]

In [24]:
pd.concat([customers, orders_shifted], axis = 1)

    customer_id name  order_id  customer_id  amount
0           1.0  Amy       NaN          NaN     NaN
1           2.0  Ben       NaN          NaN     NaN
2           3.0  Cho       NaN          NaN     NaN
10          NaN  NaN     101.0          1.0   250.0
20          NaN  NaN     102.0          1.0    80.0
30          NaN  NaN     103.0          2.0   120.0
40          NaN  NaN     104.0          4.0   300.0

In [29]:
s1 = pd.Series([10,20,30], index = ["a", "b", "c"])
s2 = pd.Series([1,2,3], index = ["b", "c", "d"])

In [31]:
s3 = s1+ s2
s3.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [45]:
orders_idx = orders.set_index("order_id")
orders_idx

          customer_id  amount
order_id
101                 1     250
102                 1      80
103                 2     120
104                 4     300

In [67]:
og = orders_idx.reset_index()
og.shape

(4, 3)

In [1]:
import pandas as pd 
import numpy as np

In [2]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "name": ["Amy", "Ben", "Cho"],
})

orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 1, 2, 4],
    "amount": [250, 80, 120, 300],
})

In [5]:
pd.merge(customers, orders, on = "customer_id", how = "inner")

   customer_id name  order_id  amount
0            1  Amy       101     250
1            1  Amy       102      80
2            2  Ben       103     120

In [10]:
pd.merge(customers, orders, on = "customer_id", how = "left")

   customer_id name  order_id  amount
0            1  Amy     101.0   250.0
1            1  Amy     102.0    80.0
2            2  Ben     103.0   120.0
3            3  Cho       NaN     NaN

In [12]:
pd.merge(customers, orders, on = "customer_id", how = "outer")

   customer_id name  order_id  amount
0            1  Amy     101.0   250.0
1            1  Amy     102.0    80.0
2            2  Ben     103.0   120.0
3            3  Cho       NaN     NaN
4            4  NaN     104.0   300.0

In [15]:
orders["amount"].apply(lambda x: "BIG" if x > 100 else "SMALL")

0      BIG
1    SMALL
2      BIG
3      BIG
Name: amount, dtype: str

In [ ]:
orrders["amount"].apply(lambda x: "BIG" if x > 100 else "SMALL")

In [28]:
orders.apply(lambda s: s.max(), axis = 0)

order_id       104
customer_id      4
amount         300
dtype: int64

In [34]:
orders[orders["amount"]>100]

   order_id  customer_id  amount
0       101            1     250
2       103            2     120
3       104            4     300

In [37]:
(orders["amount"]>100).sum()

np.int64(3)

In [43]:
rows = [{"threshold": t, "n_big":(orders["amount"]>t).sum()} for t in [100,150,200]]
pd.DataFrame(rows)

   threshold  n_big
0        100      3
1        150      2
2        200      2

In [51]:
rows = [
    {
        "threshold":t,
        "n_big":(orders["amount"]>t).sum()
    }

    for t in [100,150,200]
]

pd.DataFrame(rows)

   threshold  n_big
0        100      3
1        150      2
2        200      2

In [52]:
import sys
sys.path.append(r"C:\ml_eng_prep_2026\project-1-secom-yield")

In [53]:
len(y), len(oof), (y == 1).sum()

NameError: name 'y' is not defined

In [1]:
import pandas as pd 
import numpy as np

In [20]:
arr = np.random.randn(100, 4)*5+10

In [32]:
np.mean(arr)
np.std(arr)
z = (arr - np.mean(arr)) / np.std(arr)
z.std()

np.float64(1.0)

In [34]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [37]:
X, y = load_breast_cancer(return_X_y=True)

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=42, stratify = y)

In [49]:
model = LogisticRegression()

In [52]:
model.fit(X_train, y_train)

c:\Users\perry\miniconda3\envs\ml_eng_prep\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [55]:
preds = model.predict(X_test)

In [56]:
model.score(X_test, y_test)

0.9473684210526315

In [60]:
(y_test == preds).sum()/len(preds)

np.float64(0.9473684210526315)

In [61]:
model = LogisticRegression()

In [63]:

model.fit(X_train, y_train)

c:\Users\perry\miniconda3\envs\ml_eng_prep\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [64]:
preds = model.predict(X_test)

In [67]:
model.score(X_test, y_test)

0.9473684210526315

In [80]:
proba = model.predict_proba(X_test)
proba.shape

(114, 2)

In [81]:
print(proba[:5],preds[:5])

[[1.00000000e+00 4.99797349e-13]
 [1.71541090e-04 9.99828459e-01]
 [8.05023155e-01 1.94976845e-01]
 [6.43017023e-01 3.56982977e-01]
 [1.00000000e+00 1.13429842e-13]] [0 1 0 0 0]

In [82]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [83]:
scaler.fit(X_train)

StandardScaler()

In [91]:
scaled_x = scaler.transform(X)
scaler.mean_

array([1.40672132e+01, 1.92473626e+01, 9.15574066e+01, 6.48541099e+02,
       9.61674286e-02, 1.03868901e-01, 8.91933224e-02, 4.83439516e-02,
       1.80618022e-01, 6.28197802e-02, 3.98971868e-01, 1.21872923e+00,
       2.82255011e+00, 3.92437473e+01, 7.08365714e-03, 2.55379802e-02,
       3.25524826e-02, 1.16727824e-02, 2.07788308e-02, 3.79728374e-03,
       1.61772264e+01, 2.56472967e+01, 1.06625297e+02, 8.69026593e+02,
       1.32328923e-01, 2.54328571e-01, 2.76578191e-01, 1.13904332e-01,
       2.90865275e-01, 8.39446154e-02])

In [92]:
scaler.scale_

array([3.49553212e+00, 4.40044714e+00, 2.41226787e+01, 3.44565295e+02,
       1.34429172e-02, 5.34628148e-02, 8.16570636e-02, 3.88817548e-02,
       2.80435443e-02, 7.15154679e-03, 2.67530622e-01, 5.70894390e-01,
       1.97130469e+00, 4.17172778e+01, 3.13190654e-03, 1.84464287e-02,
       3.23346642e-02, 6.28280287e-03, 8.75425038e-03, 2.77706609e-03,
       4.76477484e+00, 6.21862498e+00, 3.31585545e+01, 5.52318965e+02,
       2.25254161e-02, 1.59706175e-01, 2.15699142e-01, 6.67105163e-02,
       6.45533961e-02, 1.83874818e-02])

In [94]:
scaler = StandardScaler()

In [95]:
scaler.fit(X_train)

StandardScaler()

In [96]:
scaler.mean_

array([1.40672132e+01, 1.92473626e+01, 9.15574066e+01, 6.48541099e+02,
       9.61674286e-02, 1.03868901e-01, 8.91933224e-02, 4.83439516e-02,
       1.80618022e-01, 6.28197802e-02, 3.98971868e-01, 1.21872923e+00,
       2.82255011e+00, 3.92437473e+01, 7.08365714e-03, 2.55379802e-02,
       3.25524826e-02, 1.16727824e-02, 2.07788308e-02, 3.79728374e-03,
       1.61772264e+01, 2.56472967e+01, 1.06625297e+02, 8.69026593e+02,
       1.32328923e-01, 2.54328571e-01, 2.76578191e-01, 1.13904332e-01,
       2.90865275e-01, 8.39446154e-02])

In [97]:
scaler.mean_.shape

(30,)

In [98]:
np.allclose(scaler.mean_, X_train.mean(axis=0))
np.allclose(scaler.scale_, X_train.std(axis=0))

True

In [99]:
X_train_s = scaler.transform(X_train)
X_test_s = scaler.transform(X_test)

In [100]:
X_train_s.mean(axis=0)[:5]

array([-4.31742554e-15,  2.24606658e-15, -7.38359313e-16,  1.71779562e-16,
        5.22695440e-15])

In [101]:
X_test_s.mean(axis=0)[:5]

array([0.08578544, 0.04796295, 0.08516978, 0.09195453, 0.07160436])

In [103]:
[a for a in dir(model) if a.endswith("_") and not a.startswith("_")]

['classes_', 'coef_', 'intercept_', 'n_features_in_', 'n_iter_']

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [6]:
X, y = load_breast_cancer(return_X_y = True)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,stratify = y, random_state = 123)

In [12]:
model = LogisticRegression()

In [13]:
model.fit(X_train, y_train)

c:\Users\perry\miniconda3\envs\ml_eng_prep\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [17]:
preds = model.predict(X_test)

In [18]:
model.score(X_test, y_test)

0.956140350877193

In [19]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [20]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [21]:
pipe = Pipeline([
    ("impute", SimpleImputer(strategy = "median")),
    ("scale", StandardScaler()),
    ("clf", LogisticRegression())

])

In [23]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('impute', SimpleImputer(strategy='median')),
                ('scale', StandardScaler()), ('clf', LogisticRegression())])

In [24]:
pipe.score(X_test, y_test)

0.9736842105263158

In [28]:
print(
pipe.named_steps["scale"].mean_,
pipe.named_steps["impute"].statistics_,
pipe.named_steps["clf"].n_iter_)

[1.41206418e+01 1.93354945e+01 9.18922857e+01 6.54669231e+02
 9.59540659e-02 1.03620176e-01 8.91111554e-02 4.86589297e-02
 1.80278462e-01 6.28967912e-02 4.06620440e-01 1.22419121e+00
 2.87283429e+00 4.07990154e+01 6.94013846e-03 2.53080571e-02
 3.22220848e-02 1.17171473e-02 2.04457099e-02 3.84765560e-03
 1.62846110e+01 2.57393187e+01 1.07372220e+02 8.84454725e+02
 1.31929275e-01 2.54306220e-01 2.74899927e-01 1.14756376e-01
 2.89631648e-01 8.44660440e-02] [1.330e+01 1.887e+01 8.589e+01 5.464e+02 9.579e-02 9.242e-02 6.195e-02
 3.334e-02 1.791e-01 6.168e-02 3.147e-01 1.127e+00 2.257e+00 2.394e+01
 6.294e-03 2.047e-02 2.611e-02 1.090e-02 1.868e-02 3.136e-03 1.491e+01
 2.548e+01 9.733e+01 6.806e+02 1.314e-01 2.119e-01 2.299e-01 1.015e-01
 2.812e-01 8.024e-02] [17]

In [31]:
len(X_train[0])

30

In [33]:
print(pipe.named_steps["scale"].mean_.shape,
pipe.named_steps["impute"].statistics_.shape,
pipe.named_steps["clf"].n_iter_)

(30,) (30,) [17]

In [36]:
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

preds = pipe.predict(X_test)
proba = pipe.predict_proba(X_test)[:,1]
print(preds, proba,
precision_score(y_test, preds),
recall_score(y_test, preds),
f1_score(y_test,preds),
roc_auc_score(y_test, preds))

[0 0 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1
 1 0 0 1 1 1 1 0 1 1 0 1 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 0 1 0 0 1
 1 0 1 0 0 0 1 0 1 1 0 1 0 1 1 0 0 1 1 0 0 1 0 1 1 0 1 1 1 0 1 1 1 0 0 1 1
 1 1 1] [4.40344128e-02 5.39983718e-07 9.99800996e-01 9.97477428e-01
 9.24665945e-01 3.60566432e-06 9.99977147e-01 1.80011187e-09
 9.90570129e-01 9.99989244e-01 9.99789499e-01 9.95011180e-01
 9.95065643e-01 9.99857180e-01 9.99503557e-01 3.15231861e-08
 9.95595401e-01 9.91550585e-01 9.88527013e-01 9.99864090e-01
 9.96190873e-01 9.99994457e-01 8.33608075e-01 8.95947541e-01
 5.13190775e-09 9.99880273e-01 9.84891884e-01 9.97682292e-01
 9.86190998e-01 4.11857064e-03 9.99306840e-01 9.77145167e-01
 1.21361130e-04 9.92846579e-01 9.37295541e-01 1.21447274e-04
 9.99861107e-01 9.80583015e-01 3.80280376e-01 6.40438088e-04
 8.05652950e-01 6.84480624e-01 8.87804558e-01 9.45035542e-01
 7.01523036e-03 9.99610194e-01 9.83305130e-01 2.19232602e-03
 9.99869571e-01 9.98784437e-01 9.15775902e-10 9.97239597e-01
 9.97216410e-01 9.82172436e-01 9.95115702e-01 1.01852676e-04
 6.79955625e-13 9.82982282e-06 5.10977162e-03 9.62635042e-01
 9.98620483e-01 9.97911785e-01 5.33272679e-01 2.45664785e-06
 2.96644849e-04 4.29176739e-01 3.28689656e-02 9.98270757e-01
 9.99953221e-01 4.69722220e-03 9.25706638e-01 1.48971562e-10
 1.99001658e-02 9.99937871e-01 9.99715953e-01 5.37923657e-06
 9.92808858e-01 1.08316280e-06 2.20059318e-09 2.52522314e-03
 9.65769842e-01 2.52631846e-05 9.99649508e-01 9.99944469e-01
 4.74701659e-03 8.53950023e-01 5.18221945e-04 9.99799710e-01
 9.77726607e-01 1.61807791e-06 3.80246479e-03 8.53931407e-01
 9.90288696e-01 2.68663470e-02 2.92734742e-01 9.41820858e-01
 6.57462664e-05 9.92506232e-01 9.97950357e-01 7.60023814e-05
 9.93367917e-01 9.99750800e-01 9.98595082e-01 4.40055658e-01
 9.97861658e-01 9.99978639e-01 9.98183259e-01 8.00919590e-05
 3.49558686e-02 9.94203673e-01 9.99919088e-01 9.99998427e-01
 9.98745018e-01 9.82121599e-01] 0.9726027397260274 0.9861111111111112 0.9793103448275862 0.9692460317460316

In [35]:
precision_score

In [37]:
tp = ((preds == 1) & (y_test ==1)).sum()
fp = ((preds == 1) & (y_test ==0)).sum()
fn =  ((preds == 0) & (y_test ==1)).sum()

In [38]:
tp / (fp+tp)

np.float64(0.9726027397260274)

In [40]:
tp/(tp + fn)

np.float64(0.9861111111111112)

In [43]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, preds)
tn, fp, fn, tp = cm.ravel()

cm

array([[40,  2],
       [ 1, 71]])

In [ ]:
tp = ((p==1)&(y==1)).sum()

fp = ((p==1)&(y==0)).sum()

fn = ((p==0)&(y==1)).sum()

In [4]:
import numpy as np
y = np.random.randint(0, 2, 20)
p = np.random.randint(0, 2, 20)

In [5]:
y

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1],
      dtype=int32)

In [6]:
p

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0],
      dtype=int32)

In [7]:
tp = ((p==1)&(y==1)).sum()

fp = ((p==1)&(y==0)).sum()

fn = ((p==0)&(y==1)).sum()

In [8]:
precision = tp / (tp+fp)

In [9]:
recall = tp / (tp+fn)

In [11]:
print(f"precision is {precision}")

print(f"recall is {recall}")

precision is 0.7777777777777778
recall is 0.5384615384615384

In [12]:
from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples = 1500,
    n_features = 20,
    weights = [0.93],
    random_state = 42,
)

In [13]:
np.bincount(y)

array([1389,  111])

In [28]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import StratifiedKFold

In [29]:
skf = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 42 )

for fold, (train_idx, test_idx) in enumerate(skf.split(X, y)):
    print(f"fold {fold}: train={len(train_idx)}, test={len(test_idx)}, "
          f"test positives={y[test_idx].sum()}")

fold 0: train=1200, test=300, test positives=22
fold 1: train=1200, test=300, test positives=22
fold 2: train=1200, test=300, test positives=22
fold 3: train=1200, test=300, test positives=22
fold 4: train=1200, test=300, test positives=23

In [ ]:
skf = StratifiedKFold(n_splits = 5, shuffle = True, random_state =42)

for FontFaceSetLoadEvent